---
- name: Set up OpenTripPlanner on Ubuntu EC2
  hosts: all
  become: yes  # This allows Ansible to use sudo
  vars:
    java_package: openjdk-21-jdk  # Adjust version as needed
    s3_bucket: ibi-snap
    otp_directory: /opt/otp
    otp_jar_path: /opt/otp/otp.jar
    otp_graph_path: /opt/otp/graph.obj
    otp_config_path: /opt/otp/otp-config.json
    otp_router_path: /opt/otp/router-config.json

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present
    - name: Install pip
      apt:
        pkg:
        - python3-boto3
        - python3-full
        - python3-botocore

    - name: Install Python packaging module
      pip:
        name: packaging
        state: present

    - name: Create OTP directory
      file:
        path: /opt/otp
        state: directory
        mode: '0755'

    - name: Download OTP JAR from S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: otp-config/otp.jar
        dest: "{{ otp_jar_path }}"
        mode: get

    - name: Download OTP graph from S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: otp-config/graph.obj
        dest: "{{ otp_graph_path }}"
        mode: get

    - name: Download OTP config from S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: otp-config/otp-config.json
        dest: "{{ otp_config_path }}"
        mode: get

    - name: Download router config from S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: otp-config/router-config.json
        dest: "{{ otp_router_path }}"
        mode: get

    - name: Create OTP systemd service file
      template:
        src: otp.service.j2
        dest: /etc/systemd/system/otp.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start OTP service
      ansible.builtin.systemd_service:
        name: otp
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Wait for OTP server to become available
      ansible.builtin.wait_for:
        port: 8080
        delay: 10