---
- name: Set up OpenTripPlanner on Ubuntu EC2
  hosts: all
  become: yes  # This allows Ansible to use sudo
  vars:
    java_package: openjdk-11-jdk  # Adjust version as needed
    s3_bucket: your-s3-bucket-name
    otp_jar_path: /opt/otp/otp.jar
    otp_graph_path: /opt/otp/graph.obj
    otp_config_path: /opt/otp/config.json

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present
    - name: Install pip
      apt:
        pkg:
        - python3-boto3
        - python3-full
        - python3-botocore

    - name: Create OTP directory
      file:
        path: /opt/otp
        state: directory
        mode: '0755'

    - name: Download OTP JAR from S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: /server/otp.jar
        dest: "{{ otp_jar_path }}"
        mode: get

    - name: Download OTP graph from S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: /server/graph.obj
        dest: "{{ otp_graph_path }}"
        mode: get

    - name: Download OTP config from S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: /server/config.json
        dest: "{{ otp_config_path }}"
        mode: get

    - name: Start OTP server
      shell: java -Xmx2G -jar {{ otp_jar_path }} --graphs {{ otp_graph_path }} --router default
      async: 1000
      poll: 0